# Source: aegis/templates/service.yaml
# Copyright 2026-present matstech
# SPDX-License-Identifier: GPL-3.0-only

apiVersion: v1
kind: Service
metadata:
  name: aegis
  labels:
    helm.sh/chart: aegis-2.1.0
    app.kubernetes.io/name: aegis
    app.kubernetes.io/instance: aegis
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    tailscale.com/proxy-group: tailscale-ingress
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: aegis
    app.kubernetes.io/instance: aegis
