global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
serversTransport:
  insecureSkipVerify: true
api:
  insecure: true
  dashboard: true
accessLog: {}
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
  # docker:
  #   endpoint: "unix:///var/run/docker.sock"
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
certificatesResolvers:
  cloudflare:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # test
      email: r.cannella.90@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"