http:
  routers:
    dex:
      rule: "Host(`login.internal.speziato.dev`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: dex
      # middlewares:
      #   - ldap@file
  services:
    dex:
      loadBalancer:
        servers:
          - url: "http://dex:5556"
