http:
  routers:
    oauth2-proxy-route:
      rule: "Host(`oauth2-proxy.internal.speziato.dev`)"
      middlewares:
        - auth-headers
      service: oauth-backend
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    oauth-backend:
      loadBalancer:
        servers:
          - url: http://oauth2-proxy:4180

  middlewares:
    auth-headers:
      headers:
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        sslHost: internal.speziato.dev
    oauth-auth-redirect:
      forwardAuth:
        address: http://oauth2-proxy:4180
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
    oauth-auth-wo-redirect:
      forwardAuth:
        address: http://oauth2-proxy:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Access-Token
          - Authorization
