http:
  routers:
    nas:
      rule: "Host(`torrents.internal.speziato.dev`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: nas
      middlewares:
        - auth-headers
        - oauth-auth-redirect
    nas-oauth:
      rule: "Host(`torrents.internal.speziato.dev`) && PathPrefix(`/oauth2/`)"
      middlewares:
        - auth-headers
      service: oauth-backend
      tls:
        certResolver: cloudflare

  services:
    nas:
      loadBalancer:
        servers:
          - url: "http://nas.fritz.box:8080"
