http:
  routers:
    nas:
      rule: "Host(`torrents.internal.speziato.dev`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: nas
      middlewares:
        - add-shebang
        - auth-headers
        - oauth-auth-redirect
    nas-oauth:
      rule: "Host(`torrents.internal.speziato.dev`) && PathPrefix(`/oauth2/`)"
      middlewares:
        - auth-headers
      service: oauth-backend
      tls:
        certResolver: cloudflare

  middlewares:
    add-shebang:
      redirectRegex:
        regex: "^https?://torrents.internal.speziato.dev/(^api.*|.*(css|png|jpg|js))$"
        replacement: "https://torrents.internal.speziato.dev/#/$1"
  services:
    nas:
      loadBalancer:
        servers:
          - url: "http://nas.fritz.box:8080"
