apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/configmap-aegis-conf.yaml
- resources/deployment-aegis.yaml
- resources/service-aegis.yaml
namespace: services
secretGenerator:
- envs:
  - secrets/keys.env
  name: aegis-keys
  type: Opaque
- envs:
  - secrets/aegis.env
  name: aegis-env
  type: Opaque
