apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-media-filebrowser.yaml
- ingress-media-filebrowser.yaml
- service-media-filebrowser.yaml
configMapGenerator:
  - name: media-filebrowser-config
    files:
      - config/config.yaml
