apiVersion: batch/v1
kind: Job
metadata:
  name: immich-db-restore
spec:
  backoffLimit: 2
  template:
    spec:
      securityContext:
        fsGroup: 26
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting restore to CloudNativePG..."
              export PGPASSWORD="${password}"
              gunzip --stdout "/backups/immich/backups/dump_migrated.sql.gz" \
                | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
                | psql --host=${host} --port=${db_port:-5432} --dbname=${dbname} --username=${user}

              echo "Restore complete."
          envFrom:
            - secretRef:
                name: immich-database
            
          volumeMounts:
            - name: backups
              mountPath: /backups
      volumes:
        - name: backups
          persistentVolumeClaim:
            claimName: backups-hostpath