apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  template:
    spec:
      containers:
        - name: vaultwarden
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
            - name: vaultwarden-data
              mountPath: /data/attachments
              $patch: delete