[env]
KUBECONFIG="{{config_root}}/kubeconfig"
TALOSCONFIG="{{config_root}}/talosconfig"

[vars]
TALOS_VERSION="1.11.5"
KUBE_VERSION="1.34.1"

[tools]
kustomize = "5.8.0"
talosctl = "{{vars.TALOS_VERSION}}"
kubectl = "{{vars.KUBE_VERSION}}"
stern = "1.33.1"
pipx = "1.8.0"
yq = "4.49.1"
helm = "latest"