server.document-root = "/var/www/html"
server.port = 8080
server.username = "1000"
server.groupname = "1000"

dir-listing.activate = "enable"
dir-listing.hide-dotfiles = "false"
dir-listing.external-css = "/theme.css"

# Logging to stdout/stderr
accesslog.filename = "/dev/stdout"
server.errorlog = "/dev/stderr"

# Writable temp paths
server.pid-file = "/tmp/lighttpd.pid"
server.upload-dirs = ( "/tmp" )