apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "zfs-dataset-128k"
