- block:
  - name: Ensure /home/{{ ansible_user }}/.config/incus-ansible/ dir exists
    file: 
      path: "/home/{{ ansible_user }}/.config/incus-ansible/"
      state: directory
    become_user: "{{ ansible_user }}"
  - name: Copying incus configuration file
    become_user: "{{ ansible_user }}"
    template:
      src: incus-config.yaml.j2
      dest: "/home/{{ ansible_user }}/.config/incus-ansible/incus-config.yaml"
  - name: Ensure "{{ incus.storage_pool }}" dir exists
    file: 
      path: "{{ incus.storage_pool }}"
      state: directory
  - name: Register config
    ansible.builtin.command: "cat /home/{{ ansible_user }}/.config/incus-ansible/incus-config.yaml"
    register: incus_config
  - name: Init incus
    command: incus admin init --preseed
    args:
      stdin: "{{ incus_config.stdout }}"
  - name: Restarting incus service
    systemd:
      daemon_reload: true
      name: incus
      enabled: true
      state: restarted
  tags:
    - incus
    - configure
