- name: Install Zabbly's incus repository
  include_tasks:
    file: zabbly-repo.yaml
  tags:
    - incus
    - repository
- name: Install incus
  include_tasks:
    file: install.yaml
  tags:
    - incus
    - install
- name: Configure incus
  include_tasks:
    file: configure.yaml
  tags:
    - incus
    - configure
- name: Configure firewall rules
  include_tasks:
    file: firewall.yaml
  tags:
    - incus
    - firewall
- name: Enable oci repositories
  include_tasks:
    file: oci.yaml
  tags:
    - incus
    - oci
- name: Install incus ui
  include_tasks:
    file: ui.yaml
  tags:
    - incus
    - ui
- name: Configure remote on local host
  include_tasks:
    file: remote.yaml
  tags:
    - incus
    - remote
