- become: false
  delegate_to: localhost
  block:
    - name: Check if localhost has incus installed
      shell: command -v incus
      changed_when: false
    - name: Set hostname fact
      set_fact:
        local_hostname: "{{lookup('pipe', 'hostname')}}"
    - name: "List configured remotes"
      shell: "incus remote list -f yaml"
      register: configured_remotes
      changed_when: false
    - name: "Check if localhost already has the {{incus.remote_incus_name}} remote"
      set_fact:
        remotes: "{{ configured_remotes.stdout | from_yaml }}"
    - debug:
        msg: "localhost {{ (incus.remote_incus_name in remotes) | ternary('already has', 'does not have') }} the remote named {{incus.remote_incus_name}}"
    - name: "Create incus token for {{local_hostname}}"
      shell: "incus config trust add {{local_hostname}} | awk -F'Client {{ local_hostname }} certificate add token:' '{print $1}' | xargs"
      register: token_output
      delegate_to: ""
      when: "incus.remote_incus_name not in remotes"
    - name: "Add remote to local incus"
      shell: "incus remote add {{incus.remote_incus_name}} {{lookup('env', 'HYPERVISOR_IP')}} --token {{token_output.stdout}} --accept-certificate"
      when: "incus.remote_incus_name not in remotes"
  rescue:
    - when: ansible_failed_task.name == 'Check if localhost already has the ' + incus.remote_incus_name + ' remote'
      ansible.builtin.debug:
        msg: 'Remote "{{incus.remote_incus_name}}" already defined'
  tags:
  - incus
  - remote
