---
- block:
  - name: Set architecture specific variables
    set_fact:
      arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
  - name: Update APT cache
    apt:
      update_cache: true
    changed_when: false
  - name: "Add {{ incus.apt_repos.zabbly_incus.name }} APT repository"
    ansible.builtin.deb822_repository:
      name: "{{ incus.apt_repos.zabbly_incus.name }}"
      types: deb
      uris: "{{ incus.apt_repos.zabbly_incus.repo }}"
      suites: "{{ incus.apt_repos.zabbly_incus.suites }}"
      components: "{{ incus.apt_repos.zabbly_incus.components }}"
      architectures: "{{arch}}"
      signed_by: "{{ incus.apt_repos.zabbly_incus.gpg_key }}"
      state: present
      enabled: true
  - name: Update APT cache
    apt:
      update_cache: true
    changed_when: false
  tags:
    - incus
    - repository
