apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-hostpath
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mnt/disk1/backups