apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: backups-hostpath