---
- name: Set architecture specific variables
  set_fact:
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Install and run Tailscale
  block:
  - name: Add Tailscale APT repository
    ansible.builtin.deb822_repository:
      name: "{{server_setup.apt_repos.tailscale.name}}"
      types: deb
      uris: "{{server_setup.apt_repos.tailscale.repo}}"
      suites: "{{server_setup.apt_repos.tailscale.suites}}"
      components: "{{server_setup.apt_repos.tailscale.components}}"
      architectures: "{{arch}}"
      signed_by: "{{server_setup.apt_repos.tailscale.gpg_key}}"
      state: present
      enabled: true
  - name: Update APT cache
    apt:
      update_cache: true
    changed_when: false
  - name: Install Tailscale package
    package:
      name: tailscale
      state: latest
  - name: Join Tailscale network
    shell: "sudo tailscale up --auth-key={{ lookup('env', 'TAILSCALE_KEY') }}"

- name: Install packages
  package:
    name: "{{server_setup.packages}}"
    state: latest

- name: Enable and configure unattended upgrades
  block:
  - name: Install apt prerequisites for automated reboots
    ansible.builtin.apt:
      name: update-notifier-common
      state: present
  - name: Create unattended upgrades configuration file
    ansible.builtin.blockinfile:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      block: |
        APT::Periodic::Update-Package-Lists "1";
        APT::Periodic::Unattended-Upgrade "1";
      marker: "// {mark} ANSIBLE MANAGED BLOCK - unattended_upgrades settings"
      create: true
      mode: "0644"
      owner: root
      group: root
    register: unattended_upgrades_config_set
  - name: Enable automated reboots
    ansible.builtin.blockinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      block: |
        Unattended-Upgrade::Automatic-Reboot "true";
        Unattended-Upgrade::Automatic-Reboot-Time "{{server_setup.unattended_updates.reboot_time}}";
      marker: "// {mark} ANSIBLE MANAGED BLOCK - unattended_upgrades settings"
      create: true
      mode: "0644"
      owner: root
      group: root
    register: unattended_upgrades_settings_set
  - name: Enable specified origins
    ansible.builtin.blockinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      block: |
        Unattended-Upgrade::Allowed-Origins {
                "${distro_id}:${distro_codename}";
                "${distro_id}:${distro_codename}-security";
                // Extended Security Maintenance; doesn't necessarily exist for
                // every release and this system may not have it installed, but if
                // available, the policy for updates is such that unattended-upgrades
                // should also install from here by default.
                "${distro_id}ESMApps:${distro_codename}-apps-security";
                "${distro_id}ESM:${distro_codename}-infra-security";
                "${distro_id}:${distro_codename}-updates";
        //      "${distro_id}:${distro_codename}-proposed";
        //      "${distro_id}:${distro_codename}-backports";
                // Tailscale
                "{{server_setup.apt_repos.tailscale.archive}}:";
        };
      marker: "// {mark} ANSIBLE MANAGED BLOCK - unattended_upgrades origin settings"
      create: true
      mode: "0644"
      owner: root
      group: root
    register: unattended_upgrades_settings_set
  - name: Dpkg reconfigure
    ansible.builtin.command:
      cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    register: dpkg_reconfigure_unattended_upgrades
    when:
      - unattended_upgrades_config_set.changed or
        unattended_upgrades_settings_set.changed
  - name: Configure cache updates timing
    ansible.builtin.lineinfile:
      path: /lib/systemd/system/apt-daily.timer
      regexp: '^OnCalendar'
      line: "OnCalendar=*-*-* {{server_setup.unattended_updates.update_time}}"
  - name: Configure cache updates timing
    ansible.builtin.lineinfile:
      path: /lib/systemd/system/apt-daily.timer
      regexp: '^RandomizedDelaySec'
      line: "RandomizedDelaySec=180"
  - name: Configure updates installation timing
    ansible.builtin.lineinfile:
      path: /lib/systemd/system/apt-daily-upgrade.timer
      regexp: '^OnCalendar'
      line: "OnCalendar=*-*-* {{server_setup.unattended_updates.install_time}}"
  - name: Configure updates installation timing offset
    ansible.builtin.lineinfile:
      path: '/lib/systemd/system/apt-daily-upgrade.timer'
      regexp: '^RandomizedDelaySec'
      line: 'RandomizedDelaySec=180'
