apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 1 
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  bootstrap:
    initdb:
      database: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - ALTER USER immich WITH SUPERUSER;
      owner: immich
      secret:
        name: immich-pg-credentials
      dataChecksums: true
      encoding: 'UTF8'
  storage:
    size: 2Gi
  postgresql:
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v0.5.3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
    shared_preload_libraries:
      - "vchord"