apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: first-backup-immich
  namespace: databases
spec:
  cluster:
    name: immich
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
