apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-immich.yaml
- podmonitor-immich.yaml

secretGenerator:
  - name: immich-pg-credentials
    type: kubernetes.io/basic-auth
    envs:
      - ./secrets/immich-pg-credentials.env
    options:
      disableNameSuffixHash: true
