apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immich-pm # needs to be different from the cluster's name, see: https://github.com/cloudnative-pg/cloudnative-pg/issues/8075#issuecomment-3670371568
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immich
  podMetricsEndpoints:
  - port: metrics
    relabelings:
    - replacement: databases/immich
      targetLabel: job
