apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  labels:
    backup: velero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs-dataset-128k