apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
- resources/deploy.yaml
- resources/ingress.yaml
- resources/pv.yaml
- resources/pvc.yaml
- resources/svc.yaml

configMapGenerator:
  - name: autoindex-conf
    files:
      - lighttpd.conf=config/lighttpd.conf
      - theme.css=config/theme.css
