[tasks.maintenance]
run = '''
#!/usr/bin/env bash
HELM_REPO_URL="https://guerzon.github.io/vaultwarden"
HELM_REPO_NAME="vaultwarden"
HELM_CHART_NAME="vaultwarden"
HELM_CHART_VERSION="0.46.2"
NAMESPACE=services
RELEASE_NAME=vaultwarden
# Helm chart repo: https://github.com/guerzon/vaultwarden/tree/main/charts/vaultwarden

helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
helm repo update
rm -rf resources/vendor
helm template ${RELEASE_NAME} ${HELM_REPO_NAME}/${HELM_CHART_NAME} --values MAINTENANCE.values.yaml --version "${HELM_CHART_VERSION}"  > deploy.maintenance.yaml
kubectl slice -f deploy.maintenance.yaml -o resources/vendor
rm deploy.maintenance.yaml
rm -f kustomization.yaml
kustomize init --autodetect --recursive --namespace "${NAMESPACE}"
kustomize edit add secret vaultwarden-admin-token --from-env-file=secrets/admin-token.env
kustomize edit remove resource patches/loadbalancer-class.yaml
kustomize edit add patch --path patches/loadbalancer-class.yaml
kustomize build . >/dev/null || (echo "Something went wrong, check upstream for changes" >&2 && exit 1)
'''