apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
- resources/job-init-config.yaml
- resources/rbac-wait-for.yaml
- resources/pvc-config.yaml
- resources/pvc-media.yaml
- resources/bazarr
- resources/jellyfin
- resources/lidarr
- resources/prowlarr
- resources/qbittorrent
- resources/radarr
- resources/sonarr

configMapGenerator:
  - name: media-server-env
    envs:
      - env/common.env
secretGenerator:
  - name: media-server-config-files
    files:
      - bazarr.yaml=./config/secrets/bazarr.yaml
      - lidarr.xml=./config/secrets/lidarr.xml
      - prowlarr.xml=./config/secrets/prowlarr.xml
      - qBittorrent.conf=./config/secrets/qBittorrent.conf
      - radarr.xml=./config/secrets/radarr.xml
      - sonarr.xml=./config/secrets/sonarr.xml